### ISSUE TITLE
.git/ref seems to be missing

### ISSUE THREAD

**Issue by zachgersh** [concourse/git-resource#153] opened 2017-10-25 18:39 UTC
Can't seem to figure this out since it echos it right after the commiter but `.git/ref` is missing when hijacking into the container.

**Comment by jgrau** [comment] 2017-11-05 20:40
What version of concourse are you on. When I started using concourse not that long ago, I had the same issue but at the same time as there was an update the file started to be created... not sure this is at all the case but it was my experience.

**Comment by chrishiestand** [comment] 2018-10-08 18:41
I noticed this happen when I `git clone`d one git repo to a new directory. The new directory didn't have `.git/ref` since that file is populated by the resource and not by git itself.

I heavily use `.git/ref` and I haven't noticed this problem anywhere else. Without more data to reproduce I'd imagine we can close this issue?

**Closed** 2018-11-27 16:31 UTC
