### ISSUE TITLE
`[ci skip]` still not respected

### ISSUE THREAD

**Issue by swtch1** [concourse/git-resource#221] opened 2018-10-18 19:45 UTC
I am opening this issue specifically in order to bring attention to [issue 18](https://github.com/concourse/git-resource/issues/18).  There was a lot of debate on 18 about workarounds but it felt like the majority of people thought the bug was hard to discover and inconsistent.  The bug happens on near identical pipelines without a direct reason that can be pointed to.  Also, many people have stated that the workarounds do not work for them and have requested that the issue be re-opened.  From the conversation I could not see why the issue was closed without a better fix so I'm just re-opening it explicitly here.

Thank you for the great software.

**Comment by kalfa** [comment] 2018-11-26 12:11
I'm not upstream, but this duplicates #196 

I agree #18  doesn't seem should be closed, it's an open issue and a workaround is not a fix.

**Comment by Yacine-A** [comment] 2019-03-07 23:25
We need that ! indeed!

**Comment by vito** [comment] 2019-03-09 16:30
duplicate of #196

**Closed by vito** 2019-03-09 16:30 UTC
