### ISSUE TITLE
Originate from branch

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/git-resource#89] opened 2016-10-23 15:43 UTC
I have a scenario that involves creating a pipeline with particular branch missing for some of the involved git repos.

I have tried many-many variants to create the branch of it is missing from the pipeline, but with no success. It is like one of this cases that whatever you try something goes wrong to the point you have felt the system was designed on purpose this to be impossible.

I think it will be nice if git-resource takes care of this seamlessly with an optional flag: originate_branch.

This will be used only if the branch is missing. There are two small changes needed to the logic: check - needs to return version that represents the originate_branch and in (in case of originate_branch revision will create the new branch.

**Comment by vito** [comment] 2016-10-24 16:01
Could you explain your use case a bit more? Not sure I understand correctly.

**Comment by ggeorgiev** [comment] 2016-10-24 16:55
I have a set of pipelines that do not include deployment - they are "dev" pipelines. They run tests, static, dynamic code analysis etc.

I would like to have an extremely easy way for developers to be able to replicate the "dev" pipelines for their even a short term dev branches - so they to have all the benefits from CI.

This means that the "dev" pipelines should have all resources and configurations per branch - which seems ok and relatively easy to achieve.

One issue that I did not find a good way to solve is how to create a missing branch from a git repository. Note the pipeline includes several git repositories, some of them maintenance - with completely autogenerated content - it should not be dev responsibility to create a new branch there or even care that it exists.

Ine thing that I do not want to compromise is providing access to git repositories from the task - else having task that creates branch if it does not exist is easy. As soon as I do not have such task relying on git-resource only - there is no good solution.

**Comment by chendrix** [comment] 2017-05-23 23:28
Closing as dupe of concourse/concourse#1172

**Closed** 2017-05-23 23:58 UTC

**Comment by marco-m** [comment] 2018-11-21 15:13
I think that this ticket has been closed for the wrong reason. Ticket concourse/concourse#1172 is about multi-branch workflow (what is now known as Spaces). Multi-branch workflow assumes that the git repo has all the feature branches already existing. This ticket on the other hand is asking for the git resource to have an option to create a branch.
