### ISSUE TITLE
Changing the resource configuration has no effect

### ISSUE THREAD

**Issue by friegger** [concourse/git-resource#27] opened 2016-01-19 15:44 UTC
Resource caching [1] prevents the git_resource from recognizing changes to the resource configuration. e.g. branch, uri

[1] https://github.com/concourse/git-resource/blob/master/assets/check#L29

**Comment by vito** [comment] 2016-01-20 06:07
Looks like this regressed, probably with 0.71. Not a bug with the git resource; we shouldn't be reusing containers at all if the source changes. Dragging this in; should be fixed soon.

**Closed** 2016-01-26 22:23 UTC
Labels: bug
