### ISSUE TITLE
reference branch, commit in a task?

### ISSUE THREAD

**Issue by jaychris** [concourse/git-resource#104] opened 2017-01-13 18:35 UTC
Is it possible to reference the branch and commit that are found by the git-resource as a parameter to another task?

For example, if my git-resource is pulling "master" and the latest ref is "ae7038b89beaf3faf237ad32818b400e98a7a0fc", is there some way to reference those if I wanted to use them in another task (a build task for example) as a notation or tag or something?

Sorry, I'm new-ish to concourse and I didn't see anything obvious in the git-resource documentation.

**Comment by nicolai86** [comment] 2017-01-23 12:14
I'm wondering the same thing. We want to use git shas as tags for docker images, and right now every job which needs this information runs `git rev-parse HEAD` as a custom task, which is super slow. Is there any way to pass this information around?

**Comment by gabro** [comment] 2017-01-30 14:04
Sounds like a dupe of this one: https://github.com/concourse/git-resource/issues/56

**Comment by nicolai86** [comment] 2017-01-30 15:34
@gabro yes it does. Fwiw we're using the rev-parse workaround but it's really slow in terms of cloning the repo over and over...

**Comment by gabro** [comment] 2017-01-30 16:43
@nicolai86 why do you need to clone the repo over and over?

Can't you simply have the repo as input and run `git rev-parse HEAD` inside the task?

**Comment by jaychris** [comment] 2017-01-30 17:21
@gabro, that's how we are handling it at the moment...

**Comment by gabro** [comment] 2017-02-22 10:23
I realized that if you need it as a file, you can simply use

`thegitresource/.git/HEAD`

For example:

```yml
- name: example-job
  plan:
  - get: a-git-repo
    trigger: true
  - put: a-docker-image
    params:
      build: a-git-repo
      tag: a-git-repo/.git/HEAD
```

**Closed** 2017-03-28 20:40 UTC
Labels: question, unscheduled

**Comment by airtonix** [comment] 2017-08-03 00:46
@gabro the idea has merit, however I think the file is not exactly going to contain what we want all the time, for example:

```
C:\Data\Projects\QCU\qcu002 [feature/merge-common-frontend ≡]> cat .git/HEAD
ref: refs/heads/feature/merge-common-frontend
```

Not sure how that would be useful as a docker tag. Perhaps you can shed light on some other file

**Comment by gabro** [comment] 2017-08-03 08:47
@airtonix on your machine (in a normal git workflow) is definitely not guaranteed to be a commit hash, but when this resources clones the repo, it then does

```bash
git checkout -q $ref
```

And - as far as I can tell - `$ref` is always going to be the commit hash in this context, since it's used as the resource version too. We've been using this expedient for the past 6 months, and it was **always** the commit we expected.
